name: PDFLibrarian
options:
  deploymentTarget:
    macOS: "13.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.larry.pdflibrarian
    SWIFT_VERSION: 5.10
targets:
  PDFLibrarian:
    type: application
    platform: macOS
    sources:
      - Sources/PDFLibrarian
    settings:
      base:
        PRODUCT_NAME: "PDF Librarian"
        INFOPLIST_KEY_CFBundleDisplayName: "PDF Librarian"
        INFOPLIST_KEY_LSMinimumSystemVersion: "13.0"
        CODE_SIGN_STYLE: Automatic
    info:
      path: Sources/PDFLibrarian/Info.plist
      properties:
        CFBundleName: "PDF Librarian"
        CFBundleDisplayName: "PDF Librarian"
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1.0.0
        NSHighResolutionCapable: true
        NSPrincipalClass: NSApplication
schemes:
  PDFLibrarian:
    build:
      targets:
        PDFLibrarian: all
    run:
      config: Debug
    archive:
      config: Release
